### ISSUE TITLE
System.InvalidCastException: Specified cast is not valid. Android

### ISSUE THREAD

**Issue by idimkk** [alexrainman/CarouselView#272]
Hello. I use this design to upload images from the archive. But I ran into the problem, if there are more than 2 pictures in the collection, then an exception appears on the third swipe(in either direction). Although I see that the picture in the background has been drawn.
**Sample Code:**
>                 var collection = new ObservableCollection<CachedImage>();
>                 foreach (IArchiveEntry entry in archive.Entries.Take(3))
>                 {
>                     using (var stream = entry.OpenEntryStream())
>                     {
>                         collection.Add(new CachedImage() { Source = ImageSource.FromStream(() => stream), DownsampleWidth = 1080, Aspect = Aspect.AspectFill });
>                     }
>                 }
>                 myCarousel.ItemsSource = collection;

**Stack Trace:**

> 11-23 16:46:53.397 I/MonoDroid(17789): UNHANDLED EXCEPTION:
> 11-23 16:46:53.438 I/MonoDroid(17789): System.InvalidCastException: Specified cast is not valid.
> 11-23 16:46:53.439 I/MonoDroid(17789):   at CarouselView.FormsPlugin.Android.CarouselViewRenderer+PageAdapter.DestroyItem (Android.Views.ViewGroup container, System.Int32 position, Java.Lang.Object object) [0x00000] in <987b2fd695d94047809eece606991303>:0 
> 11-23 16:46:53.439 I/MonoDroid(17789):   at Android.Support.V4.View.PagerAdapter.n_DestroyItem_Landroid_view_ViewGroup_ILjava_lang_Object_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_container, System.Int32 position, System.IntPtr native__object) [0x00018] in <fc4222de5c684a9abf7cc4821baac4cd>:0 
> 11-23 16:46:53.439 I/MonoDroid(17789):   at (wrapper dynamic-method) System.Object:d322a05b-a794-41bf-893c-295270a85c1a (intptr,intptr,intptr,int,intptr)

**Comment by alexrainman** [comment]
Which version of the plugin?

**Comment by alexrainman** [comment]
This was corrected at version 5.0.1

**Comment by idimkk** [comment]
Tried on the latest version (5.0.1) and 4.4.6.
There is an error in both versions.

**Comment by alexrainman** [comment]
You sure? I cannot reproduce this. It was happening in version 5.0.0 because i was trying to cast CachedImage into ViewGroup but i fixed that in version 5.0.1

**Comment by idimkk** [comment]
Absolutely.
If you want to. We can look at it remotely. If this is convenient for you.
Or I can record a video.

**Comment by idimkk** [comment]
Please do not close the problem. I can provide you with a project on which you can try.

**Comment by alexrainman** [comment]
I already released version 5.0.2 :)

**Comment by idimkk** [comment]
Yes, I noticed it later than I wrote! **Thanks a lot** - it's a wonderful library, which makes me very happy.
The problem is solved in the release 5.0.2.

**Comment by ozzioma** [comment]
Thanks for making this plugin.
I'm still experiencing this with version 5.20.
I'm working on a .Net standard 2.0 PCL.
I noticed there is NO complete example of how to use this plugin.
I think it should be pretty simple to give a complete example, one in xaml or in code.
Spent hours figuring out how to make it work....
Also, the code samples are a bit confusing.
The  Demo project MainPage.xaml leaves no clues as to how the binding or the DataTemplate specs works. 
Any pointers as to how to use this plugin or maybe a complete example?

**Comment by alexrainman** [comment]
There’s not complete example? I bet u havent read the README :)

**Comment by ozzioma** [comment]
Hi Alex,
Thanks for taking time to reply.
I have gone throuhgh the README and the samples.
Below is the code for the ContentPage I'm using the plugin on,
What could be wrong?

`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="DemoApp.Views.AppIntro3"
              xmlns:slide="clr-namespace:CarouselView.FormsPlugin.Abstractions;assembly=CarouselView.FormsPlugin.Abstractions"
xmlns:cv="clr-namespace:Xamarin.Forms;assembly=Xamarin.Forms.CarouselView"

             xmlns:lottie="clr-namespace:Lottie.Forms;assembly=Lottie.Forms"
           xmlns:controls="clr-namespace:DemoApp.Views.Controls;assembly=DemoApp"
           xmlns:iconize="clr-namespace:Plugin.Iconize;assembly=Plugin.Iconize"
           xmlns:ffimageloading="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"
           xmlns:fftransformations="clr-namespace:FFImageLoading.Transformations;assembly=FFImageLoading.Transformations"
           NavigationPage.HasBackButton="False" NavigationPage.HasNavigationBar="False">

    <ContentPage.Content>

        <StackLayout HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">


            <Grid>
                <RowDefinitionCollection>
                    <RowDefinition Height="0.1*"></RowDefinition>
                    <RowDefinition Height="0.6*"></RowDefinition>
                    <RowDefinition Height="0.3*"></RowDefinition>
                </RowDefinitionCollection>

                <StackLayout Grid.Row="0" Orientation="Horizontal" HorizontalOptions="CenterAndExpand">

                    <Label Text="Some header" TextColor="#ffb74d" FontSize="Large" VerticalOptions="CenterAndExpand" HorizontalOptions="Center" 
                  VerticalTextAlignment="Center"  HorizontalTextAlignment="Center">
                    </Label>
                </StackLayout>

                <StackLayout  Grid.Row="1"  Margin="20,10,10,20" Orientation="Horizontal" HorizontalOptions="CenterAndExpand">




                    <slide:CarouselViewControl x:Name="slideshow" Position="0"
        ItemsSource="{Binding Items}" ShowArrows="true" ShowIndicators="true"  Orientation="Horizontal">
                            <slide:CarouselViewControl.ItemTemplate>
                                <DataTemplate>

                                    <ContentView HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">

                                        <StackLayout Orientation="Vertical" Spacing="12">

                                            <ffimageloading:CachedImage DownsampleToViewSize="true"  VerticalOptions="Center"
                          Source ="{Binding SlideImage}" Aspect="AspectFill" />

                                            <Label VerticalOptions="Center"
                            Text="{Binding SlideTitle}" FontAttributes="Bold" FontSize="21" TextColor="#ffb74d"></Label>

                                            <Label VerticalOptions="Center" 
                            Text="{Binding SlideText}" FontAttributes="Bold" FontSize="18" TextColor="#00b2b2"></Label>


                                        </StackLayout>
                                    </ContentView>

                                </DataTemplate>
                            </slide:CarouselViewControl.ItemTemplate>

                        </slide:CarouselViewControl>

                </StackLayout>

                <StackLayout Orientation="Vertical" Margin="0,10" HorizontalOptions="End" VerticalOptions="End" Spacing="15">

                    <controls:RoundButton ButtonText="Sign in" TextColor="White" TextSize="20"  HeightRequest="45" WidthRequest="300"
                    FrameColor="#FFB74D" FrameRadius="18" FrameMargin="1,1" FramePadding="2,2" OnClick="OnLogin"/>

                    <controls:RoundButton ButtonText="Sign in" TextColor="#666" TextSize="20"  HeightRequest="45" WidthRequest="300"
                   BorderColor="#FFB74D"  FrameColor="#fff" FrameRadius="18" FrameMargin="1,1" FramePadding="2,2" 
                                   OnClick="OnSignUp"/>


                </StackLayout>


            </Grid>


        </StackLayout>



    </ContentPage.Content>
</ContentPage>`


Thanks

**Comment by PowerUzer** [comment]
@ozzioma I was having the same issue, change ContentPage to ContentView in your XAML and you will be good to go.
