### ISSUE TITLE
[UWP] PositionSelectedCommand' bound command not executing

### ISSUE THREAD

**Issue by Cheatmagnet** [alexrainman/CarouselView#413]
Binding a command to the PositionSelectedCommand triggers fine on Android (yet to test on iOS) but fails on the UWP implementation (?) 
From your notes it seemed as if it would would work for all platforms (perhaps i'm missing something?)

**Comment by AndreiMisiukevich** [comment]
Hi @Cheatmagnet 
you can try this plugin https://github.com/AndreiMisiukevich/CardView

**Comment by Cheatmagnet** [comment]
Thanks!

**Comment by alexrainman** [comment]
Fixed. Next release.

**Comment by Ruddy2007** [comment]
@alexrainman Was this fixed? I am still seeing the issue. iOS and Android are working but UWP doesn't get triggered.
