### ISSUE TITLE
Please update to include fix in CirclePageIndicator

### ISSUE THREAD

**Issue by Quax82** [alexrainman/CarouselView#508]
Hi Alex,

in https://github.com/alexrainman/CirclePageIndicator/issues/1 you solved an issue that causes my app(s) to crash. Could you update the CarouselView project to incorporate this bugfix, please?

Thank you,
Jens

**Comment by alexrainman** [comment]
Jens, i will be releasing a new carousel soon, just been dealing with some health related issues. For now, just update the circlepageindicator package in your projects and that should work. Thanks

**Comment by Quax82** [comment]
Hi Alex,

no problem. Of course, health is one of the most important things in life.

I did try to update. However, in that case, the ViewPager reference cannot be resolved and installing that nuget package does not help (still "... viewpager cannot be resolved.".

Thanks for your help and sharing your code,
Jens

**Comment by alexrainman** [comment]
Mmm other users said it worked for them. Anyway, i am close to release date.

**Comment by Quax82** [comment]
I am pretty sure it is something with my project configuration. However, I was not smart enough to solve it, yet.

Thank you

**Comment by lewcianci** [comment]
Hey @Quax82, you're installing the updated CirclePageIndicator into your Android project yeah? Not the shared project?

**Comment by lewcianci** [comment]
Also @alexrainman sorry to hear about your health problems.  You mentioned you were travelling quite recently and it sounds like you've gotten ill quite soon after so no doubt you've had a constant few months :( I hope you feel better soon.... developing when sick is not fun/borderline impossible

**Comment by Quax82** [comment]
@lewcianci
Yes, that is what I am doing. The unresolved external error also takes place in the Android project.

**Comment by Quax82** [comment]
This is the error message btw (after adding CirclePageIndicator 1.0.3 to the Android project):

 error XA2002: Can not resolve reference: `Xamarin.Android.Support.ViewPager`, referenced by `Com.ViewPagerIndicator`. Please add a NuGet package or assembly reference for `Xamarin.Android.Support.ViewPager`, or remove the reference to `Com.ViewPagerIndicator`.

**Comment by Quax82** [comment]
@lewcianci  @alexrainman 
Ok, no chance for me to get it working before the release. I also tried to pull the repo and recompile it but when updating to Xamarin.Forms 3.6 (which is necessary in order to update the CirclePageIndicator), the code breaks. As said before, installing CirclePageIndicator 1.0.3 directly into my project does not work as well with the above mentioned error. So I am going to wait until Alex is fine again.

**Comment by alexrainman** [comment]
Well im healthy and back in businesses. CarouselView 6.0 will be out soon.

**Comment by Quax82** [comment]
@alexrainman
Good to hear you are healthy again. I did not want to increase pressure or anything but I thought maybe you guys had an idea for the time before the release. Please take your time.

**Comment by Quax82** [comment]
Found the solution in https://github.com/alexrainman/CarouselView/issues/489 . I had Android 8.1 as my target framework and changed it to Android 9.0. Now, when installing CirclePageIndicator 1.0.3, the project compiles fine and the app does not crash anymore.

**Comment by LeoJHarris** [comment]
@alexrainman CarouselView 6.0, how soon?

**Comment by CarlosEMF2** [comment]
> Jens, lanzaré un nuevo carrusel pronto, solo traté algunos problemas relacionados con la salud. Por ahora, simplemente actualice el paquete de indicador de página de círculo en sus proyectos y eso debería funcionar. Gracias

Tengo el mismo problema, no puedo instalar  los nuget de circlepageindicator por la versión de .NETStandard,Version=v2.0

**Comment by CarlosEMF2** [comment]
> Bueno estoy sano y estoy de vuelta en el negocio. CarouselView 6.0 saldrá pronto.

CarouselView 6.0, ¿qué tan pronto?

**Comment by developer9969** [comment]
Hi there
CarouselView 6.0 really? that would be fantastic! any ideas when

**Comment by CarlosEMF2** [comment]
???????

**Comment by Abdulbasha** [comment]
After Updating XF4.0.0.425677 and Changed the Target Framework ( Android 8.1 ), Still i am facing the same issue and getting exception like Unable to activate instance of type Com.ViewPagerIndicator.CirclePageIndicator from native handle 0x7fe4ce06c4 . Can you please provide us the solution.

**Comment by alexrainman** [comment]
I am back! Releasing new version in the next 2 weeks. This issue will be corrected.

**Comment by Abdulbasha** [comment]
My issue is solved now. I Changed the Target Framework ( Android 9.0 ) and updated the Xamarin.Android.CirclePageIndicator to 1.0.3. Thanks to @BryanSan.

**Comment by bluekuen** [comment]
@Abdulbasha Hello Abdul,
i installed Xamarin.Android.CirclePageIndicator 1.0.3 in my Xamarin.Android Project but the CarouselView is still crashing with JNI handle error on Android 9.0. Do you have an idea why it doesn't work?

**Comment by CarlosEMF2** [comment]
and the update?

**Comment by lewcianci** [comment]
This probably doesn't help, but due to this issue (and other issues) I moved my codebase to flutter.  This functionality is natively implemented by the framework, you can see a video of it here: https://www.youtube.com/watch?v=J1gE9xvph-A.

If you can switch to a different framework it might be a good idea... Xamarin hasn't had this functionality natively ever.  And probably never will.  It took me weeks to port my code across, but now I'm done, and I'm not waiting on this package to be updated anymore :)

**Comment by LeoJHarris** [comment]
@lewcianci A spec was drafted up for CarouselView earlier this year https://github.com/xamarin/Xamarin.Forms/issues/4996 and was released (I think in XF 4.1), there are some some existing issues with CarouselView in XF and its been a long time coming but I think CarouselView in XF becoming stable wont be to far away off. Its a shame its taken this long however to get there.

**Comment by alexrainman** [comment]
As i promised, i will release version 6.0, i just want it to be a real bump in functionality and stability.

**Comment by guillaumebadin** [comment]
hello @alexrainman could you push the release on github just for test it ?
We use your library on Android 9 and we have a serious crash.

**Comment by Phenek** [comment]
This issue should be open.

**Comment by guillaumebadin** [comment]
> As i promised, i will release version 6.0, i just want it to be a real bump in functionality and stability.

@alexrainman could you just backport the build Android 9 problem ? I guess for your update you will break some api... So It will be super cool to just resolve the build problem
