### ISSUE TITLE
NullReferenceException on Android after Xamarin Forms update to 4.4.0.991265

### ISSUE THREAD

**Issue by mkzeta** [alexrainman/CarouselView#557]
I updated my Xamarin Forms project from Xamarin Forms 4.3.0.991250 to 4.4.0.991265 and now get the following NullReferenceException when I start my Android project. iOS works.

<pre>
  at CarouselView.FormsPlugin.Android.CarouselViewRenderer.OnElementChanged (Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1[TElement] e) [0x00132] in <892bb6a09e5d43ddbe9591d58bbf4c0e>:0 
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000b8] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:231 
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00027] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:128 
  at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x0001f] in D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:344 
  at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x000af] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:138 
  at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x00139] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:334 
  at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:110 
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x00007] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:440 
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000d5] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:234 
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00027] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:128 
  at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x0001f] in D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:344 
  at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x000af] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:138 
  at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x00139] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:334 
  at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:110 
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x00007] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:440 
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000d5] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:234 
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00027] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:128 
  at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x0001f] in D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:344 
  at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x000af] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:138 
  at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x00139] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:334 
  at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:110 
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x00007] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:440 
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000d5] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:234 
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00027] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:128 
  at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x0001f] in D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:344 
  at Xamarin.Forms.Platform.Android.ScrollViewContainer.set_ChildView (Xamarin.Forms.View value) [0x0002f] in D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\ScrollViewContainer.cs:37 
  at Xamarin.Forms.Platform.Android.ScrollViewRenderer.LoadContent () [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\ScrollViewRenderer.cs:364 
  at Xamarin.Forms.Platform.Android.ScrollViewRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x000cf] in D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\ScrollViewRenderer.cs:97 
  at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x0001f] in D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:344 
  at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x000af] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:138 
  at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x00139] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:334 
  at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:110 
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x00007] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:440 
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000d5] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:234 
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00027] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:128 
  at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Support.V4.App.FragmentManager fragmentManager, Android.Content.Context context) [0x00031] in D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:391 
  at Xamarin.Forms.Platform.Android.AppCompat.FragmentContainer.OnCreateView (Android.Views.LayoutInflater inflater, Android.Views.ViewGroup container, Android.OS.Bundle savedInstanceState) [0x00008] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\FragmentContainer.cs:56 
  at Android.Support.V4.App.Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_inflater, System.IntPtr native_container, System.IntPtr native_savedInstanceState) [0x00020] in <4778c530db8c472280798b576df9ad7a>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.56(intptr,intptr,intptr,intptr,intptr)
</pre>

**Comment by SharpMobileCode** [comment]
I'm seeing the exact same issue with an identical stack trace as well when upgrading to Xamarin.Forms 4.4.0.991265.

**Comment by SharpMobileCode** [comment]
I can't say for sure, but looking at the stack traces and code I'm thinking that pull request #549 might fix this issue.  It's been open since Oct.

**Comment by mkzeta** [comment]
I can confirm, that #549 is the solution for this. But when I compile a new version I get a _NullReferenceException_ at  line 420 of _CarouselViewImplementation_

<pre>
void SetNativeView()
{
    if (orientationChanged)
    {
        var inflater = AViews.LayoutInflater.From(_context);

        // Orientation BP
        if (Element.Orientation == CarouselViewOrientation.Horizontal)
            nativeView = inflater.Inflate(Resource.Layout.horizontal_viewpager, null);
        else
            nativeView = inflater.Inflate(Resource.Layout.vertical_viewpager, null);

        //  -- > Will return null. Why? <--
        viewPager = nativeView.FindViewById<ViewPager>(Resource.Id.pager);

        orientationChanged = false;
    }
    viewPager.Adapter = new PageAdapter(Element);
</pre>

### Steps to reproduce

- Clone repository and build
- Implement fix from #549 
- Rebuild solution
- Reference libs in own project with Xamarin 4.4.0.991265
- Debug

**Comment by SharpMobileCode** [comment]
I ended up porting over to the new built-in Xamarin Forms [CarouselView](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/carouselview/layout) and the new (but experimental) [IndicatorView](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/indicatorview).   

The Interfaces are very similar to this library so the code changes were pretty minimal.  They perform functionally the same from what I can tell.  I think I'm just going to stick with the new built-in stuff for now because I can't afford to be blocked.

**Comment by alexrainman** [comment]
I will take a look at this before releasing a new version.

**Comment by alexrainman** [comment]
I cannot reproduce this in my latest code. It just work out of the box with fix #549

**Comment by mfranc28** [comment]
Same error here. Update to last version of Xam forms and debug on Android 10

**Comment by JMNewsome** [comment]
I am receiving this error as well on Android

**Comment by nobiGT** [comment]
Same here on Android Emulator (API 24) and Moto G5 Plus (API 28), so I just downgraded Xamarin Forms from 4.4.0.991265 to 4.3.0.991250 and it looks OK for now.

**Comment by higher-faster-better** [comment]
I am also getting perfect same error after I upgraded Xamarin Forms to 4.4.0.991265

**Comment by mfranc28** [comment]
Yes seems is not compatible with last version of Xamarin Forms, I need to downgrade to 4.2.2.x only for Android

**Comment by alexrainman** [comment]
Who can provide a demo project reproducing the issue so i can try with my latest code?

**Comment by erichedstrom** [comment]
I get the crash as soon as I put the CarouselViewControl into a ScrollView using Xamarin Forms 4.4.0. It looks like #549 should fix it but I haven't tested that.

I created a [test project](https://github.com/erichedstrom/CarouselViewControl-557)  here to demonstrate, but the ScrollView is what it boils down to.

**Comment by alexrainman** [comment]
Why you need to put the Carousel into a ScrollView?

**Comment by SharpMobileCode** [comment]
> Why you need to put the Carousel into a ScrollView?

In my case, I have content below the carousel view that requires vertical scrolling.

**Comment by erichedstrom** [comment]
@SharpMobileCode Thanks for the pointer to the Forms built-in CarouselView.

@alexrainman I also have content below the carousel that the user has to scroll to see. It looks like [this change](https://github.com/xamarin/Xamarin.Forms/commit/8931dbd8eeb592da42b1f281ad0d97afc127daff) is what's causing issues.

**Comment by mustafadikyar** [comment]
> > Why you need to put the Carousel into a ScrollView?
> 
> In my case, I have content below the carousel view that requires vertical scrolling.

Does anyone have a workaround before updating?

**Comment by AmrAlSayed0** [comment]
Here is the stack trace I am getting if anyone needs it. Anyone found a workaround yet?
```
Exception Type : System.NullReferenceException
Message : Object reference not set to an instance of an object.
Source : mscorlib
Data : No Data
HelpLink : No HelpLink
HResult  : -2147467261

at CarouselView.FormsPlugin.Android.CarouselViewRenderer.OnElementChanged (Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1[TElement] e) [0x00132] in <892bb6a09e5d43ddbe9591d58bbf4c0e>:0
at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000b8] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:231
at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00027] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:128
at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x0001f] in D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:344
at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x000af] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:138
at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x00139] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:334
at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:110
at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x00007] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:440
at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000d5] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:234
at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00027] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:128
at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x0001f] in D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:344
at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x000af] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:138
at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x00139] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:334
at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:110
at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x00007] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:440
at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000d5] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:234
at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00027] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:128
at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x0001f] in D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:344
at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x000af] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:138
at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x00139] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:334
at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:110
at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x00007] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:440
at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000d5] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:234
at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00027] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:128
at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x0001f] in D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:344
at Xamarin.Forms.Platform.Android.ScrollViewContainer.set_ChildView (Xamarin.Forms.View value) [0x0002f] in D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\ScrollViewContainer.cs:37
at Xamarin.Forms.Platform.Android.ScrollViewRenderer.LoadContent () [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\ScrollViewRenderer.cs:364
at Xamarin.Forms.Platform.Android.ScrollViewRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x000cf] in D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\ScrollViewRenderer.cs:97
at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x0001f] in D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:344
at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x000af] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:138
at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x00139] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:334
at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:110
at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x00007] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:440
at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000d5] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:234
at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00027] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:128
at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x0001f] in D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:344
at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x000af] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:138
at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x00139] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:334
at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:110
at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x00007] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:440
at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000d5] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:234
at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00027] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:128
at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x0001f] in D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:344
at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x000af] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:138
at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x00139] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:334
at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:110
at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x00007] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:440
at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000d5] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:234
at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00027] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:128
at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x0001f] in D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:344
at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x000af] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:138
at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x00139] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:334
at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:110
at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x00007] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:440
at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000d5] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:234
at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00027] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:128
at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x0001f] in D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:344
at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x000af] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:138
at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x00139] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:334
at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:110
at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x00007] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:440
at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000d5] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:234
at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00027] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:128
at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x0001f] in D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:344
at Xamarin.Forms.Platform.Android.AppCompat.Platform+ModalContainer..ctor (Android.Content.Context context, Xamarin.Forms.Page modal) [0x00031] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\Platform.cs:435
at Xamarin.Forms.Platform.Android.AppCompat.Platform.PresentModal (Xamarin.Forms.Page modal, System.Boolean animated) [0x0000d] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\Platform.cs:389
at Xamarin.Forms.Platform.Android.AppCompat.Platform.Xamarin.Forms.INavigation.PushModalAsync (Xamarin.Forms.Page modal, System.Boolean animated) [0x00055] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\Platform.cs:164
at Xamarin.Forms.Application+NavigationImpl.OnPushModal (Xamarin.Forms.Page modal, System.Boolean animated) [0x0007d] in D:\a\1\s\Xamarin.Forms.Core\Application.cs:398
at Prism.Navigation.PageNavigationService+<>c__DisplayClass41_0.<ProcessNavigationForContentPage>b__0 () [0x0003c] in d:\a\1\s\Source\Xamarin\Prism.Forms\Navigation\PageNavigationService.cs:492
at Prism.Navigation.PageNavigationService.DoNavigateAction (Xamarin.Forms.Page fromPage, System.String toSegment, Xamarin.Forms.Page toPage, Prism.Navigation.INavigationParameters parameters, System.Func`1[TResult] navigationAction, System.Action`1[T] onNavigationActionCompleted) [0x00143] in d:\a\1\s\Source\Xamarin\Prism.Forms\Navigation\PageNavigationService.cs:704
at Prism.Navigation.PageNavigationService.ProcessNavigationForContentPage (Xamarin.Forms.Page currentPage, System.String nextSegment, System.Collections.Generic.Queue`1[T] segments, Prism.Navigation.INavigationParameters parameters, System.Nullable`1[T] useModalNavigation, System.Boolean animated) [0x001a1] in d:\a\1\s\Source\Xamarin\Prism.Forms\Navigation\PageNavigationService.cs:490
at Prism.Navigation.PageNavigationService.ProcessNavigation (Xamarin.Forms.Page currentPage, System.Collections.Generic.Queue`1[T] segments, Prism.Navigation.INavigationParameters parameters, System.Nullable`1[T] useModalNavigation, System.Boolean animated) [0x001ca] in d:\a\1\s\Source\Xamarin\Prism.Forms\Navigation\PageNavigationService.cs:365
at Prism.Navigation.PageNavigationService.NavigateInternal (System.Uri uri, Prism.Navigation.INavigationParameters parameters, System.Nullable`1[T] useModalNavigation, System.Boolean animated) [0x000f9] in d:\a\1\s\Source\Xamarin\Prism.Forms\Navigation\PageNavigationService.cs:322
```

**Comment by DominicV21** [comment]
Any idea when this is going to be fixed?

**Comment by alessandrofrancesconi** [comment]
I've ended up using the new official [Xamarin.Forms.CarouselView](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/carouselview/).
It is available since 4.4 and the synthax is pretty identical to the one used by this plugin.

**Comment by ponnumittathani** [comment]
I'm experiencing the same issue when upgrading xamarin forms to 4.5.0.356,(CarouselView.Forms Plugin(used version 5.2.0) results a NullReferenceException in Android).
Any fix available?
<img width="957" alt="StackTraceScreenshot 2020-03-16 at 1 10 45 PM" src="https://user-images.githubusercontent.com/62234575/76739860-dd113500-6792-11ea-809a-0c86c6908d56.png">

**Comment by shubhambhosale** [comment]
Anyone found solution to fix the issue, because still replicating with latest Xamarin Forms version.

**Comment by alessandrofrancesconi** [comment]
> Anyone found solution to fix the issue, because still replicating with latest Xamarin Forms version.

Can my comment be helpful? https://github.com/alexrainman/CarouselView/issues/557#issuecomment-593088783

**Comment by shubhambhosale** [comment]
Thanks for the reply. Yes, your comment will help, but it is not working on Android only and works very well on iOS. So, it would be nice if this issue resolved.

**Comment by alessandrofrancesconi** [comment]
To me, it is working fine on both OS

**Comment by shubhambhosale** [comment]
I have updated the Xamarin.Forms to latest version i.e. 4.5. After that this plugin stopped working on Android. But it still works on iOS.
So, if you have found any fix for this plugin it would help us.

**Comment by shubhambhosale** [comment]
#560 - If we are using the CarouselView in ScrollView, we are able reproduce the issue. 
@alexrainman as you have mentioned that you have fixed the issue. Please let us know how to fix the issue.

**Comment by nbsoftware** [comment]
Same here. Upgraded project to Android X using latest Xamarin Forms 4.5 and I get the same exception :

```
[AndroidRuntime] android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
[AndroidRuntime]   at CarouselView.FormsPlugin.Android.CarouselViewRenderer.OnElementChanged (Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1[TElement] e) [0x00132] in <892bb6a09e5d43ddbe9591d58bbf4c0e>:0 
[AndroidRuntime]   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000c0] in <9e919e3d32554840a213a0a951bd96a0>:0 
[AndroidRuntime]   at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x0001f] in <9e919e3d32554840a213a0a951bd96a0>:0 
[AndroidRuntime]   at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x000c0] in <9e919e3d32554840a213a0a951bd96a0>:0 
[AndroidRuntime]   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00033] in <9e919e04-01 15:20:29.602 E/AndroidRuntime( 7001):   at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x0016c] in <9e919e3d32554840a213a0a951bd96a0>:0 
[AndroidRuntime]   at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in <9e919e3d32554840a213a0a951bd96a0>:0 
[AndroidRuntime]   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000dd] in <9e919e3d32554840a213a0a951bd96a0>:0 
[AndroidRuntime]   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00033] in <9e919e3d32554840a213a0a951bd96a0>:0 
[AndroidRuntime]   at Xamarin.Forms.Platform.Android.ScrollViewContainer.set_ChildVie04-01 15:20:29.602 E/AndroidRuntime( 7001):   at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x0001f] in <9e919e3d32554840a213a0a951bd96a0>:0 
[AndroidRuntime]   at Xamarin.Forms.Platform.Android.ScrollViewRenderer.LoadContent () [0x00011] in <9e919e3d32554840a213a0a951bd96a0>:0 
[AndroidRuntime]   at Xamarin.Forms.Platform.Android.ScrollViewRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x000cf] in <9e919e3d32554840a213a0a951bd96a0>:0 
[AndroidRuntime]   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms04-01 15:20:29.602 E/AndroidRuntime( 7001):   at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x0001f] in <9e919e3d32554840a213a0a951bd96a0>:0 
[AndroidRuntime]   at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x000c0] in <9e919e3d32554840a213a0a951bd96a0>:0 
[AndroidRuntime]   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x00007] in <9e919e3d32554840a213a0a951bd96a0>:0 
[AndroidRuntime]   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000dd] in <9e919e3d32554840a213a0a951bd96a0>:0 
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.jav.VisualElement element) [0x00033] in <9e919e3d32554840a213a0a951bd96a0>:0 
[AndroidRuntime]   at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, AndroidX.Fragment.App.FragmentManager fragmentManager, Android.Content.Context context) [0x00031] in <9e919e3d32554840a213a0a951bd96a0>:0 
[AndroidRuntime]   at Xamarin.Forms.Platform.Android.AppCompat.FragmentContainer.OnCreateView (Android.Views.LayoutInflater inflater, Android.Views.ViewGroup container, Android.OS.Bundle savedInstanceState) [0x0001b] in <9e919e3d32554840a213a0a951bd96a0>:0 
[AndroidRuntime]   at AndroidX.Fragment.App.Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_inflater, System.IntPtr native_container, System.IntPtr native_savedInstanceState) [0x00020] in <b76de9b16cb343a5bac3158989a50655>:0 
[AndroidRuntime] 	at crc64720bb2db43a66fe9.FragmentContainer.n_onCreateView(Native Method)
[AndroidRuntime] 	at crc64720bb2db43a66fe9.FragmentContainer.onCreateView(FragmentContainer.java:41)
[AndroidRuntime] 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2698)
[AndroidRuntime] 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
[AndroidRuntime] 	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
[AndroidRuntime] 	at android.os.Handler.handleCallback(Handler.java:883)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:100)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:214)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:7356)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
[Process] Sending signal. PID: 7001 SIG: 9
```

**Comment by ashlar64** [comment]
I am getting this issue as well.  When the CarouselViewControl version 5.2 is inside a ScrollView in a Android app it crashes.  When you use CarouselViewControl version 5.0.2 with the Xamarin.Forms 4.5.0.530 it doesn't crash.   Ohh Xamarin....

**Comment by sikandaramla** [comment]
And I for once, didn't understand how is it supposed to be a Xamarin issue? Isn't it an issue with CarouselViewControl?

**Comment by sikandaramla** [comment]
> I am getting this issue as well. When the CarouselViewControl version 5.2 is inside a ScrollView in a Android app it crashes. When you use CarouselViewControl version 5.0.2 with the Xamarin.Forms 4.5.0.530 it doesn't crash. Ohh Xamarin....

And I for once, didn't understand how is it supposed to be a Xamarin issue? Isn't it an issue with CarouselViewControl?

**Comment by ashlar64** [comment]
> > I am getting this issue as well. When the CarouselViewControl version 5.2 is inside a ScrollView in a Android app it crashes. When you use CarouselViewControl version 5.0.2 with the Xamarin.Forms 4.5.0.530 it doesn't crash. Ohh Xamarin....
> 
> And I for once, didn't understand how is it supposed to be a Xamarin issue? Isn't it an issue with CarouselViewControl?

Yes I believe it's a CarouselViewControl issue....I just was giving details on what makes it crash and a work around by using a older version of CarouselViewControl.  "Ohh Xamarin" --- Is just me being a bit exasperated by Xamarin in general.

**Comment by bigblackus** [comment]
Hi Guys,

I encountered the same problem after upgrade to Xamarin.Forms 4.5.0.530. After moving the CarouselViewControl outside the Scrollview, the problem was solved. It is working fine now.

**Comment by rudyspano** [comment]
Hello,

Same problem with last XF 4.5.0.

After a debug session:

It seems that in the constuctor of CarouselViewRenderer
` public CarouselViewRenderer(Context context) : base(context)
        {
            _context = context;

            // KeyboardService code
            var activity = _context as Activity;
            if (activity != null)
                keyboardService = new SoftKeyboardService(activity);
        }
`
activity is null => then keyboardService is null => then a NRE occurs at the last instruction of OnElementChanged manipulating this reference:

`keyboardService.VisibilityChanged += KeyboardService_VisibilityChanged;`
and
`keyboardService.VisibilityChanged -= KeyboardService_VisibilityChanged;`

@alexrainman, I guess Xamarin Forms behavior has changed a bit (perhaps a bug). I think you should at least protect usage of keyboardService that can be null. Or get CurrentActivity in a different way.

Anyway, I put a very dirty workaround on my side for the moment:

...

KeyboardService_VisibilityChanged is then not attached. The optimization related to this event handler is not required for me (Carousel + Keyboard display) 

I hope it will help

**Comment by tvm-anand** [comment]
It is solved after updating xamarin to version 4.6.0.800

**Comment by nbsoftware** [comment]
This is still happening for me with 5.2 version and latest XF 4.8.0.1451

**Comment by nbsoftware** [comment]
Sadly, I also ended up using XF's built-in CarouselView and IndicatorView - doesn't crash.

**Comment by alexrainman** [comment]
Going to do one last release of this plugin in the next few days.

**Comment by delimaes** [comment]
I tested with several configurations. This error occurs only on Android with Xamarin.Forms 4.8.0.1451 and 4.8.0.1534. When I downgraded Xamarin.Forms to version 4.8.0.1364, the error didn't happen anymore.

I am using Xamarin.FFImageLoading version 2.4.11.982 with `CachedImageRenderer.InitImageViewHandler()` and binding `CarouselViewControl.ItemsSource` to a `List<CachedImage>`:

```
new List<CachedImage>()
{
    new CachedImage {
        Source = string.IsNullOrEmpty(imageUrl) ? "no_image.jpeg" : imageUrl,
        DownsampleToViewSize = true,
        Aspect = Aspect.AspectFit
    }
};
```

**Comment by nbsoftware** [comment]
Hey Alex,

Do you still intend to produce a newer version in an attempt to fix / workaround this issue?

XF's IndicatorView is not working so well for me on iOS so... ;)

**Comment by alexrainman** [comment]
Expect a new version with this issue fixed soon.

**Comment by ArtjomP** [comment]
Hello @alexrainman ! 
Do you have any estimations regarding the new version release date?

**Comment by 33Infinity** [comment]
I am able to reproduce this using Xamarin.Forms 4.8.0.1560 and CarouselView.FormsPlugin v5.2.0. Works fine in iOS so defaulted to out of box Carousel for Android

**Comment by xhashimks** [comment]
@alexrainman Waiting for the new release 👍

**Comment by xhashimks** [comment]
@alexrainman Please let us know the new release updates..

**Comment by peshexod** [comment]
The issue is still persisting in the versions from 4.8.0.1451. 

0xFFFFFFFFFFFFFFFF in System.Diagnostics.Debugger.Mono_UnhandledException_internal
0x1 in System.Diagnostics.Debugger.Mono_UnhandledException at /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/corlib/System.Diagnostics/Debugger.cs:125,4
0x33 in Android.Runtime.DynamicMethodNameCounter.45
0x144 in CarouselView.FormsPlugin.Android.CarouselViewRenderer.OnElementChanged
0xD3 in Xamarin.Forms.Platform.Android.VisualElementRenderer<CarouselView.FormsPlugin.Abstractions.CarouselViewControl>.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:245,4
0x3A in Xamarin.Forms.Platform.Android.VisualElementRenderer<CarouselView.FormsPlugin.Abstractions.CarouselViewControl>.Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:135,4
0x21 in Xamarin.Forms.Platform.Android.Platform.CreateRenderer at D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:350,4
0xC4 in Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:140,6
0x176 in Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:351,6
0x8 in Xamarin.Forms.Platform.Android.VisualElementPackager.Load at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:112,4
0x8 in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.SetPackager at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:470,4
0xF0 in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:248,5
0x3A in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:135,4
0x21 in Xamarin.Forms.Platform.Android.Platform.CreateRenderer at D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:350,4
0xC4 in Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:140,6
0x176 in Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:351,6
0x8 in Xamarin.Forms.Platform.Android.VisualElementPackager.Load at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:112,4
0x8 in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.SetPackager at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:470,4
0xF0 in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:248,5
0x3A in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:135,4
0x21 in Xamarin.Forms.Platform.Android.Platform.CreateRenderer at D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:350,4
0xC4 in Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:140,6
0x176 in Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:351,6
0x8 in Xamarin.Forms.Platform.Android.VisualElementPackager.Load at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:112,4
0x8 in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.SetPackager at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:470,4
0xF0 in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:248,5
0x3A in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:135,4
0x21 in Xamarin.Forms.Platform.Android.Platform.CreateRenderer at D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:350,4
0xC4 in Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:140,6
0x176 in Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:351,6
0x8 in Xamarin.Forms.Platform.Android.VisualElementPackager.Load at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:112,4
0x8 in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.SetPackager at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:470,4
0xF0 in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:248,5
0x3A in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:135,4
0x21 in Xamarin.Forms.Platform.Android.Platform.CreateRenderer at D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:350,4
0xC4 in Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:140,6
0x176 in Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:351,6
0x8 in Xamarin.Forms.Platform.Android.VisualElementPackager.Load at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:112,4
0x8 in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.SetPackager at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:470,4
0xF0 in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:248,5
0x3A in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:135,4
0x21 in Xamarin.Forms.Platform.Android.Platform.CreateRenderer at D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:350,4
0xC4 in Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:140,6
0x176 in Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:351,6
0x8 in Xamarin.Forms.Platform.Android.VisualElementPackager.Load at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:112,4
0x8 in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.SetPackager at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:470,4
0xF0 in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:248,5
0x3A in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:135,4
0x21 in Xamarin.Forms.Platform.Android.Platform.CreateRenderer at D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:350,4
0x41 in Xamarin.Forms.Platform.Android.ScrollViewContainer.set_ChildView at D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\ScrollViewContainer.cs:35,6
0x11 in Xamarin.Forms.Platform.Android.ScrollViewRenderer.LoadContent at D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\ScrollViewRenderer.cs:373,4
0xD0 in Xamarin.Forms.Platform.Android.ScrollViewRenderer.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\ScrollViewRenderer.cs:103,5
0x21 in Xamarin.Forms.Platform.Android.Platform.CreateRenderer at D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:350,4
0xC4 in Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:140,6
0x176 in Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:351,6
0x8 in Xamarin.Forms.Platform.Android.VisualElementPackager.Load at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:112,4
0x8 in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.SetPackager at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:470,4
0xF0 in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:248,5
0x3A in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:135,4
0x21 in Xamarin.Forms.Platform.Android.Platform.CreateRenderer at D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:350,4
0xC4 in Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:140,6
0x176 in Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:351,6
0x8 in Xamarin.Forms.Platform.Android.VisualElementPackager.Load at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:112,4
0x8 in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.Page>.SetPackager at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:470,4
0xF0 in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.Page>.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:248,5
0x3A in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.Page>.Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:135,4
0x33 in Xamarin.Forms.Platform.Android.Platform.CreateRenderer at D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:397,4
0x1B in Xamarin.Forms.Platform.Android.AppCompat.FragmentContainer.OnCreateView at D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\FragmentContainer.cs:64,5
0x24 in AndroidX.Fragment.App.Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_ at D:\a\1\s\generated\androidx.fragment.fragment\obj\Release\monoandroid90\generated\src\AndroidX.Fragment.App.Fragment.cs:1876,4
0x23 in Android.Runtime.DynamicMethodNameCounter.45

**Comment by xhashimks** [comment]
Is this fixed in latest version?

**Comment by ArtjomP** [comment]
@xhashimks works well for me

**Comment by xhashimks** [comment]
@ArtjomP So these error messages are not see in playstore crash reports after upgrading to latest?

**Comment by ArtjomP** [comment]
@xhashimks I didn't notice any problems in the production with the latest version.
Did you?
